In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
df=pd.read_csv("Breast Cancer METABRIC.csv")

In [3]:
df.head()

Patient ID  Age at Diagnosis Type of Breast Surgery    Cancer Type  \
0    MB-0000             75.65             Mastectomy  Breast Cancer   
1    MB-0002             43.19      Breast Conserving  Breast Cancer   
2    MB-0005             48.87             Mastectomy  Breast Cancer   
3    MB-0006             47.68             Mastectomy  Breast Cancer   
4    MB-0008             76.97             Mastectomy  Breast Cancer   

                        Cancer Type Detailed Cellularity Chemotherapy  \
0           Breast Invasive Ductal Carcinoma         NaN           No   
1           Breast Invasive Ductal Carcinoma        High           No   
2           Breast Invasive Ductal Carcinoma        High          Yes   
3  Breast Mixed Ductal and Lobular Carcinoma    Moderate          Yes   
4  Breast Mixed Ductal and Lobular Carcinoma        High          Yes   

  Pam50 + Claudin-low subtype  Cohort ER status measured by IHC  ...  \
0                 claudin-low     1.0                   Positve  ...   
1                        LumA     1.0                   Positve  ...   
2                        LumB     1.0                   Positve  ...   
3                        LumB     1.0                   Positve  ...   
4                        LumB     1.0                   Positve  ...   

  Overall Survival Status  PR Status Radio Therapy  \
0                  Living   Negative           Yes   
1                  Living   Positive           Yes   
2                Deceased   Positive            No   
3                  Living   Positive           Yes   
4                Deceased   Positive           Yes   

  Relapse Free Status (Months) Relapse Free Status     Sex  \
0                       138.65        Not Recurred  Female   
1                        83.52        Not Recurred  Female   
2                       151.28            Recurred  Female   
3                       162.76        Not Recurred  Female   
4                        18.55            Recurred  Female   

  3-Gene classifier subtype Tumor Size Tumor Stage  Patient's Vital Status  
0                 ER-/HER2-       22.0         2.0                  Living  
1     ER+/HER2- High Prolif       10.0         1.0                  Living  
2                       NaN       15.0         2.0         Died of Disease  
3                       NaN       25.0         2.0                  Living  
4     ER+/HER2- High Prolif       40.0         2.0         Died of Disease  

[5 rows x 34 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Patient ID                      2509 non-null   object 
 1   Age at Diagnosis                2498 non-null   float64
 2   Type of Breast Surgery          1955 non-null   object 
 3   Cancer Type                     2509 non-null   object 
 4   Cancer Type Detailed            2509 non-null   object 
 5   Cellularity                     1917 non-null   object 
 6   Chemotherapy                    1980 non-null   object 
 7   Pam50 + Claudin-low subtype     1980 non-null   object 
 8   Cohort                          2498 non-null   float64
 9   ER status measured by IHC       2426 non-null   object 
 10  ER Status                       2469 non-null   object 
 11  Neoplasm Histologic Grade       2388 non-null   float64
 12  HER2 status measured by SNP6    19

In [5]:
df.isnull().sum()

Patient ID                          0
Age at Diagnosis                   11
Type of Breast Surgery            554
Cancer Type                         0
Cancer Type Detailed                0
Cellularity                       592
Chemotherapy                      529
Pam50 + Claudin-low subtype       529
Cohort                             11
ER status measured by IHC          83
ER Status                          40
Neoplasm Histologic Grade         121
HER2 status measured by SNP6      529
HER2 Status                       529
Tumor Other Histologic Subtype    135
Hormone Therapy                   529
Inferred Menopausal State         529
Integrative Cluster               529
Primary Tumor Laterality          639
Lymph nodes examined positive     266
Mutation Count                    152
Nottingham prognostic index       222
Oncotree Code                       0
Overall Survival (Months)         528
Overall Survival Status           528
PR Status                         529
Radio Therap

In [6]:
df.shape

(2509, 34)

In [7]:
df["Patient's Vital Status"].unique()

array(['Living', 'Died of Disease', 'Died of Other Causes', nan],
      dtype=object)

In [8]:
df['Overall Survival Status'].unique()

array(['Living', 'Deceased', nan], dtype=object)

In [9]:
df['Overall Survival Status'].value_counts()

Overall Survival Status
Deceased    1144
Living       837
Name: count, dtype: int64

In [10]:
df['Overall Survival Status'].isnull().sum()

np.int64(528)

In [11]:
df['Overall Survival Status']=df['Overall Survival Status'].map({'Living':0, 'Deceased':1, np.nan:1})

In [12]:
df['Overall Survival Status'].isnull().sum()

np.int64(0)

In [13]:
df['Overall Survival Status'].value_counts()

Overall Survival Status
1    1672
0     837
Name: count, dtype: int64

In [14]:
df['Overall Survival Status']=df['Overall Survival Status'].astype(int)

In [15]:
df.drop('Patient ID', axis=1, inplace=True)

In [16]:
df.head(5)

Age at Diagnosis Type of Breast Surgery    Cancer Type  \
0             75.65             Mastectomy  Breast Cancer   
1             43.19      Breast Conserving  Breast Cancer   
2             48.87             Mastectomy  Breast Cancer   
3             47.68             Mastectomy  Breast Cancer   
4             76.97             Mastectomy  Breast Cancer   

                        Cancer Type Detailed Cellularity Chemotherapy  \
0           Breast Invasive Ductal Carcinoma         NaN           No   
1           Breast Invasive Ductal Carcinoma        High           No   
2           Breast Invasive Ductal Carcinoma        High          Yes   
3  Breast Mixed Ductal and Lobular Carcinoma    Moderate          Yes   
4  Breast Mixed Ductal and Lobular Carcinoma        High          Yes   

  Pam50 + Claudin-low subtype  Cohort ER status measured by IHC ER Status  \
0                 claudin-low     1.0                   Positve  Positive   
1                        LumA     1.0                   Positve  Positive   
2                        LumB     1.0                   Positve  Positive   
3                        LumB     1.0                   Positve  Positive   
4                        LumB     1.0                   Positve  Positive   

   ...  Overall Survival Status PR Status Radio Therapy  \
0  ...                        0  Negative           Yes   
1  ...                        0  Positive           Yes   
2  ...                        1  Positive            No   
3  ...                        0  Positive           Yes   
4  ...                        1  Positive           Yes   

  Relapse Free Status (Months) Relapse Free Status     Sex  \
0                       138.65        Not Recurred  Female   
1                        83.52        Not Recurred  Female   
2                       151.28            Recurred  Female   
3                       162.76        Not Recurred  Female   
4                        18.55            Recurred  Female   

  3-Gene classifier subtype Tumor Size  Tumor Stage  Patient's Vital Status  
0                 ER-/HER2-       22.0          2.0                  Living  
1     ER+/HER2- High Prolif       10.0          1.0                  Living  
2                       NaN       15.0          2.0         Died of Disease  
3                       NaN       25.0          2.0                  Living  
4     ER+/HER2- High Prolif       40.0          2.0         Died of Disease  

[5 rows x 33 columns]

In [17]:
df['Age at Diagnosis'].isnull().sum()

np.int64(11)

In [18]:
df[df['Age at Diagnosis']==0]

Empty DataFrame
Columns: [Age at Diagnosis, Type of Breast Surgery, Cancer Type, Cancer Type Detailed, Cellularity, Chemotherapy, Pam50 + Claudin-low subtype, Cohort, ER status measured by IHC, ER Status, Neoplasm Histologic Grade, HER2 status measured by SNP6, HER2 Status, Tumor Other Histologic Subtype, Hormone Therapy, Inferred Menopausal State, Integrative Cluster, Primary Tumor Laterality, Lymph nodes examined positive, Mutation Count, Nottingham prognostic index, Oncotree Code, Overall Survival (Months), Overall Survival Status, PR Status, Radio Therapy, Relapse Free Status (Months), Relapse Free Status, Sex, 3-Gene classifier subtype, Tumor Size, Tumor Stage, Patient's Vital Status]
Index: []

[0 rows x 33 columns]

In [19]:
df.columns

Index(['Age at Diagnosis', 'Type of Breast Surgery', 'Cancer Type',
       'Cancer Type Detailed', 'Cellularity', 'Chemotherapy',
       'Pam50 + Claudin-low subtype', 'Cohort', 'ER status measured by IHC',
       'ER Status', 'Neoplasm Histologic Grade',
       'HER2 status measured by SNP6', 'HER2 Status',
       'Tumor Other Histologic Subtype', 'Hormone Therapy',
       'Inferred Menopausal State', 'Integrative Cluster',
       'Primary Tumor Laterality', 'Lymph nodes examined positive',
       'Mutation Count', 'Nottingham prognostic index', 'Oncotree Code',
       'Overall Survival (Months)', 'Overall Survival Status', 'PR Status',
       'Radio Therapy', 'Relapse Free Status (Months)', 'Relapse Free Status',
       'Sex', '3-Gene classifier subtype', 'Tumor Size', 'Tumor Stage',
       'Patient's Vital Status'],
      dtype='object')

In [20]:
df.columns=df.columns.str.strip()
df.columns

Index(['Age at Diagnosis', 'Type of Breast Surgery', 'Cancer Type',
       'Cancer Type Detailed', 'Cellularity', 'Chemotherapy',
       'Pam50 + Claudin-low subtype', 'Cohort', 'ER status measured by IHC',
       'ER Status', 'Neoplasm Histologic Grade',
       'HER2 status measured by SNP6', 'HER2 Status',
       'Tumor Other Histologic Subtype', 'Hormone Therapy',
       'Inferred Menopausal State', 'Integrative Cluster',
       'Primary Tumor Laterality', 'Lymph nodes examined positive',
       'Mutation Count', 'Nottingham prognostic index', 'Oncotree Code',
       'Overall Survival (Months)', 'Overall Survival Status', 'PR Status',
       'Radio Therapy', 'Relapse Free Status (Months)', 'Relapse Free Status',
       'Sex', '3-Gene classifier subtype', 'Tumor Size', 'Tumor Stage',
       'Patient's Vital Status'],
      dtype='object')

In [21]:
df[df['Age at Diagnosis'].isnull()]

Age at Diagnosis Type of Breast Surgery    Cancer Type  \
2055               NaN                    NaN  Breast Cancer   
2143               NaN                    NaN  Breast Cancer   
2144               NaN                    NaN  Breast Cancer   
2318               NaN                    NaN  Breast Cancer   
2320               NaN                    NaN  Breast Cancer   
2324               NaN                    NaN  Breast Cancer   
2496               NaN                    NaN  Breast Cancer   
2498               NaN                    NaN  Breast Cancer   
2506               NaN                    NaN  Breast Cancer   
2507               NaN                    NaN  Breast Cancer   
2508               NaN                    NaN  Breast Cancer   

           Cancer Type Detailed Cellularity Chemotherapy  \
2055  Invasive Breast Carcinoma         NaN          NaN   
2143  Invasive Breast Carcinoma         NaN          NaN   
2144  Invasive Breast Carcinoma         NaN          NaN   
2318  Invasive Breast Carcinoma         NaN          NaN   
2320  Invasive Breast Carcinoma         NaN          NaN   
2324  Invasive Breast Carcinoma         NaN          NaN   
2496  Invasive Breast Carcinoma         NaN          NaN   
2498  Invasive Breast Carcinoma         NaN          NaN   
2506  Invasive Breast Carcinoma         NaN          NaN   
2507  Invasive Breast Carcinoma         NaN          NaN   
2508  Invasive Breast Carcinoma         NaN          NaN   

     Pam50 + Claudin-low subtype  Cohort ER status measured by IHC ER Status  \
2055                         NaN     NaN                       NaN       NaN   
2143                         NaN     NaN                       NaN       NaN   
2144                         NaN     NaN                       NaN       NaN   
2318                         NaN     NaN                       NaN       NaN   
2320                         NaN     NaN                       NaN       NaN   
2324                         NaN     NaN                       NaN       NaN   
2496                         NaN     NaN                       NaN       NaN   
2498                         NaN     NaN                       NaN       NaN   
2506                         NaN     NaN                       NaN       NaN   
2507                         NaN     NaN                       NaN       NaN   
2508                         NaN     NaN                       NaN       NaN   

      ...  Overall Survival Status PR Status Radio Therapy  \
2055  ...                        1       NaN           NaN   
2143  ...                        1       NaN           NaN   
2144  ...                        1       NaN           NaN   
2318  ...                        1       NaN           NaN   
2320  ...                        1       NaN           NaN   
2324  ...                        1       NaN           NaN   
2496  ...                        1       NaN           NaN   
2498  ...                        1       NaN           NaN   
2506  ...                        1       NaN           NaN   
2507  ...                        1       NaN           NaN   
2508  ...                        1       NaN           NaN   

     Relapse Free Status (Months) Relapse Free Status     Sex  \
2055                          NaN                 NaN  Female   
2143                          NaN                 NaN  Female   
2144                          NaN                 NaN  Female   
2318                          NaN                 NaN  Female   
2320                          NaN                 NaN  Female   
2324                          NaN                 NaN  Female   
2496                          NaN                 NaN  Female   
2498                          NaN                 NaN  Female   
2506                          NaN                 NaN  Female   
2507                          NaN                 NaN  Female   
2508                          NaN                 NaN  Female   

     3-Gene classifier subtyp

In [22]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2498 non-null   float64
 1   Type of Breast Surgery          1955 non-null   object 
 2   Cancer Type                     2509 non-null   object 
 3   Cancer Type Detailed            2509 non-null   object 
 4   Cellularity                     1917 non-null   object 
 5   Chemotherapy                    1980 non-null   object 
 6   Pam50 + Claudin-low subtype     1980 non-null   object 
 7   Cohort                          2498 non-null   float64
 8   ER status measured by IHC       2426 non-null   object 
 9   ER Status                       2469 non-null   object 
 10  Neoplasm Histologic Grade       2388 non-null   float64
 11  HER2 status measured by SNP6    1980 non-null   object 
 12  HER2 Status                     19

In [23]:
mean=df['Age at Diagnosis'].mean()

In [24]:
mean

np.float64(60.420300240192155)

In [25]:
df['Age at Diagnosis']=df['Age at Diagnosis'].fillna(mean)

In [26]:
df['Age at Diagnosis'].isnull().sum()

np.int64(0)

In [27]:
df[df['Age at Diagnosis'].isnull()]

Empty DataFrame
Columns: [Age at Diagnosis, Type of Breast Surgery, Cancer Type, Cancer Type Detailed, Cellularity, Chemotherapy, Pam50 + Claudin-low subtype, Cohort, ER status measured by IHC, ER Status, Neoplasm Histologic Grade, HER2 status measured by SNP6, HER2 Status, Tumor Other Histologic Subtype, Hormone Therapy, Inferred Menopausal State, Integrative Cluster, Primary Tumor Laterality, Lymph nodes examined positive, Mutation Count, Nottingham prognostic index, Oncotree Code, Overall Survival (Months), Overall Survival Status, PR Status, Radio Therapy, Relapse Free Status (Months), Relapse Free Status, Sex, 3-Gene classifier subtype, Tumor Size, Tumor Stage, Patient's Vital Status]
Index: []

[0 rows x 33 columns]

In [28]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          1955 non-null   object 
 2   Cancer Type                     2509 non-null   object 
 3   Cancer Type Detailed            2509 non-null   object 
 4   Cellularity                     1917 non-null   object 
 5   Chemotherapy                    1980 non-null   object 
 6   Pam50 + Claudin-low subtype     1980 non-null   object 
 7   Cohort                          2498 non-null   float64
 8   ER status measured by IHC       2426 non-null   object 
 9   ER Status                       2469 non-null   object 
 10  Neoplasm Histologic Grade       2388 non-null   float64
 11  HER2 status measured by SNP6    1980 non-null   object 
 12  HER2 Status                     19

In [29]:
df.isnull().sum()

Age at Diagnosis                    0
Type of Breast Surgery            554
Cancer Type                         0
Cancer Type Detailed                0
Cellularity                       592
Chemotherapy                      529
Pam50 + Claudin-low subtype       529
Cohort                             11
ER status measured by IHC          83
ER Status                          40
Neoplasm Histologic Grade         121
HER2 status measured by SNP6      529
HER2 Status                       529
Tumor Other Histologic Subtype    135
Hormone Therapy                   529
Inferred Menopausal State         529
Integrative Cluster               529
Primary Tumor Laterality          639
Lymph nodes examined positive     266
Mutation Count                    152
Nottingham prognostic index       222
Oncotree Code                       0
Overall Survival (Months)         528
Overall Survival Status             0
PR Status                         529
Radio Therapy                     529
Relapse Free

In [30]:
df['Type of Breast Surgery'].unique()

array(['Mastectomy', 'Breast Conserving', nan], dtype=object)

In [31]:
df['Type of Breast Surgery'].mode()

0    Mastectomy
Name: Type of Breast Surgery, dtype: object

In [32]:
df['Type of Breast Surgery']=df['Type of Breast Surgery'].map({'Mastectomy':1, 'Breast Conserving':0, np.nan:1})

In [33]:
df['Type of Breast Surgery'].unique()

array([1, 0])

In [34]:
df['Type of Breast Surgery']=df['Type of Breast Surgery'].astype(int)

In [35]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   object 
 3   Cancer Type Detailed            2509 non-null   object 
 4   Cellularity                     1917 non-null   object 
 5   Chemotherapy                    1980 non-null   object 
 6   Pam50 + Claudin-low subtype     1980 non-null   object 
 7   Cohort                          2498 non-null   float64
 8   ER status measured by IHC       2426 non-null   object 
 9   ER Status                       2469 non-null   object 
 10  Neoplasm Histologic Grade       2388 non-null   float64
 11  HER2 status measured by SNP6    1980 non-null   object 
 12  HER2 Status                     19

In [36]:
df['Cancer Type'].unique()

array(['Breast Cancer', 'Breast Sarcoma'], dtype=object)

In [37]:
df['Cancer Type'].value_counts()

Cancer Type
Breast Cancer     2506
Breast Sarcoma       3
Name: count, dtype: int64

In [38]:
df['Cancer Type']=df['Cancer Type'].map({'Breast Cancer':1, 'Breast Sarcoma':0})

In [39]:
df['Cancer Type'].value_counts()

Cancer Type
1    2506
0       3
Name: count, dtype: int64

In [40]:
df['Cancer Type']=df['Cancer Type'].astype(int)

In [41]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cancer Type Detailed            2509 non-null   object 
 4   Cellularity                     1917 non-null   object 
 5   Chemotherapy                    1980 non-null   object 
 6   Pam50 + Claudin-low subtype     1980 non-null   object 
 7   Cohort                          2498 non-null   float64
 8   ER status measured by IHC       2426 non-null   object 
 9   ER Status                       2469 non-null   object 
 10  Neoplasm Histologic Grade       2388 non-null   float64
 11  HER2 status measured by SNP6    1980 non-null   object 
 12  HER2 Status                     19

In [42]:
df['Cancer Type Detailed'].unique()

array(['Breast Invasive Ductal Carcinoma',
       'Breast Mixed Ductal and Lobular Carcinoma',
       'Breast Invasive Lobular Carcinoma', 'Invasive Breast Carcinoma',
       'Breast Invasive Mixed Mucinous Carcinoma', 'Breast Angiosarcoma',
       'Breast', 'Metaplastic Breast Cancer'], dtype=object)

In [43]:
df['Cancer Type Detailed'].value_counts()

Cancer Type Detailed
Breast Invasive Ductal Carcinoma             1865
Breast Mixed Ductal and Lobular Carcinoma     269
Breast Invasive Lobular Carcinoma             192
Invasive Breast Carcinoma                     133
Breast Invasive Mixed Mucinous Carcinoma       25
Breast                                         21
Breast Angiosarcoma                             2
Metaplastic Breast Cancer                       2
Name: count, dtype: int64

In [44]:
encoded=df.groupby('Cancer Type Detailed')['Overall Survival Status'].mean()

In [45]:
df['Cancer_Type_Detailed']=df['Cancer Type Detailed'].map(encoded)

In [46]:
df.drop('Cancer Type Detailed', axis=1, inplace=True)

In [47]:
df['Cancer_Type_Detailed']

0       0.653083
1       0.653083
2       0.653083
3       0.706320
4       0.706320
          ...   
2504    0.819549
2505    0.819549
2506    0.819549
2507    0.819549
2508    0.819549
Name: Cancer_Type_Detailed, Length: 2509, dtype: float64

In [48]:
df['Cancer_Type_Detailed']=df['Cancer_Type_Detailed'].astype(float)

In [49]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     1917 non-null   object 
 4   Chemotherapy                    1980 non-null   object 
 5   Pam50 + Claudin-low subtype     1980 non-null   object 
 6   Cohort                          2498 non-null   float64
 7   ER status measured by IHC       2426 non-null   object 
 8   ER Status                       2469 non-null   object 
 9   Neoplasm Histologic Grade       2388 non-null   float64
 10  HER2 status measured by SNP6    1980 non-null   object 
 11  HER2 Status                     1980 non-null   object 
 12  Tumor Other Histologic Subtype  23

In [50]:
df['Cellularity'].unique()

array([nan, 'High', 'Moderate', 'Low'], dtype=object)

In [51]:
df['Cellularity'].value_counts()

Cellularity
High        965
Moderate    737
Low         215
Name: count, dtype: int64

In [52]:
df['Cellularity'].isnull().sum()

np.int64(592)

In [53]:
df['Cellularity']=df['Cellularity'].map({np.nan:1, 'High':1, 'Moderate':2, 'Low':0})

In [54]:
df['Cellularity'].isnull().sum()

np.int64(0)

In [55]:
df['Cellularity']=df['Cellularity'].astype(int)

In [56]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    1980 non-null   object 
 5   Pam50 + Claudin-low subtype     1980 non-null   object 
 6   Cohort                          2498 non-null   float64
 7   ER status measured by IHC       2426 non-null   object 
 8   ER Status                       2469 non-null   object 
 9   Neoplasm Histologic Grade       2388 non-null   float64
 10  HER2 status measured by SNP6    1980 non-null   object 
 11  HER2 Status                     1980 non-null   object 
 12  Tumor Other Histologic Subtype  23

In [57]:
df['Chemotherapy'].unique()

array(['No', 'Yes', nan], dtype=object)

In [58]:
df['Chemotherapy'].value_counts()

Chemotherapy
No     1568
Yes     412
Name: count, dtype: int64

In [59]:
df['Chemotherapy'].isnull().sum()

np.int64(529)

In [60]:
df['Chemotherapy']=df['Chemotherapy'].map({np.nan:1,'No':1, 'Yes' :0})

In [61]:
df['Chemotherapy'].unique()

array([1, 0])

In [62]:
df['Chemotherapy'].isnull().sum()

np.int64(0)

In [63]:
df['Chemotherapy']=df['Chemotherapy'].astype(int)

In [64]:
df.head()

Age at Diagnosis  Type of Breast Surgery  Cancer Type  Cellularity  \
0             75.65                       1            1            1   
1             43.19                       0            1            1   
2             48.87                       1            1            1   
3             47.68                       1            1            2   
4             76.97                       1            1            1   

   Chemotherapy Pam50 + Claudin-low subtype  Cohort ER status measured by IHC  \
0             1                 claudin-low     1.0                   Positve   
1             1                        LumA     1.0                   Positve   
2             0                        LumB     1.0                   Positve   
3             0                        LumB     1.0                   Positve   
4             0                        LumB     1.0                   Positve   

  ER Status  Neoplasm Histologic Grade  ... PR Status Radio Therapy  \
0  Positive                        3.0  ...  Negative           Yes   
1  Positive                        3.0  ...  Positive           Yes   
2  Positive                        2.0  ...  Positive            No   
3  Positive                        2.0  ...  Positive           Yes   
4  Positive                        3.0  ...  Positive           Yes   

  Relapse Free Status (Months) Relapse Free Status     Sex  \
0                       138.65        Not Recurred  Female   
1                        83.52        Not Recurred  Female   
2                       151.28            Recurred  Female   
3                       162.76        Not Recurred  Female   
4                        18.55            Recurred  Female   

  3-Gene classifier subtype Tumor Size  Tumor Stage  Patient's Vital Status  \
0                 ER-/HER2-       22.0          2.0                  Living   
1     ER+/HER2- High Prolif       10.0          1.0                  Living   
2                       NaN       15.0          2.0         Died of Disease   
3                       NaN       25.0          2.0                  Living   
4     ER+/HER2- High Prolif       40.0          2.0         Died of Disease   

   Cancer_Type_Detailed  
0              0.653083  
1              0.653083  
2              0.653083  
3              0.706320  
4              0.706320  

[5 rows x 33 columns]

In [65]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    2509 non-null   int64  
 5   Pam50 + Claudin-low subtype     1980 non-null   object 
 6   Cohort                          2498 non-null   float64
 7   ER status measured by IHC       2426 non-null   object 
 8   ER Status                       2469 non-null   object 
 9   Neoplasm Histologic Grade       2388 non-null   float64
 10  HER2 status measured by SNP6    1980 non-null   object 
 11  HER2 Status                     1980 non-null   object 
 12  Tumor Other Histologic Subtype  23

In [66]:
df['Pam50 + Claudin-low subtype'].unique()

array(['claudin-low', 'LumA', 'LumB', 'Normal', nan, 'Her2', 'Basal',
       'NC'], dtype=object)

In [67]:
encoded1=df.groupby('Pam50 + Claudin-low subtype')['Overall Survival Status'].mean()

In [68]:
df['CPam50low_subtype']=df['Pam50 + Claudin-low subtype'].map(encoded1)

In [69]:
df['CPam50low_subtype'].unique()

array([0.43119266, 0.54      , 0.66315789, 0.53378378,        nan,
       0.70089286, 0.55023923, 0.83333333])

In [70]:
mean1=df['CPam50low_subtype'].mean()

In [71]:
mean1

np.float64(0.5772727272727273)

In [72]:
df['CPam50low_subtype']=df['CPam50low_subtype'].fillna(mean1)

In [73]:
df['CPam50low_subtype'].unique()

array([0.43119266, 0.54      , 0.66315789, 0.53378378, 0.57727273,
       0.70089286, 0.55023923, 0.83333333])

In [74]:
df['CPam50low_subtype']=df['CPam50low_subtype'].astype(float)


In [75]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 34 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    2509 non-null   int64  
 5   Pam50 + Claudin-low subtype     1980 non-null   object 
 6   Cohort                          2498 non-null   float64
 7   ER status measured by IHC       2426 non-null   object 
 8   ER Status                       2469 non-null   object 
 9   Neoplasm Histologic Grade       2388 non-null   float64
 10  HER2 status measured by SNP6    1980 non-null   object 
 11  HER2 Status                     1980 non-null   object 
 12  Tumor Other Histologic Subtype  23

In [76]:
df.drop('Pam50 + Claudin-low subtype', axis=1, inplace=True)

In [77]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    2509 non-null   int64  
 5   Cohort                          2498 non-null   float64
 6   ER status measured by IHC       2426 non-null   object 
 7   ER Status                       2469 non-null   object 
 8   Neoplasm Histologic Grade       2388 non-null   float64
 9   HER2 status measured by SNP6    1980 non-null   object 
 10  HER2 Status                     1980 non-null   object 
 11  Tumor Other Histologic Subtype  2374 non-null   object 
 12  Hormone Therapy                 19

In [78]:
df['Cohort'].unique()

array([ 1.,  2.,  3.,  5.,  4.,  9.,  7.,  6., nan,  8.])

In [79]:
mean2=df['Cohort'].mean()

In [80]:
mean2

np.float64(2.900320256204964)

In [81]:
df['Cohort'].value_counts()

Cohort
1.0    809
3.0    763
2.0    288
4.0    238
5.0    170
7.0    105
8.0     82
9.0     40
6.0      3
Name: count, dtype: int64

In [82]:
df['Cohort'].isnull().sum()

np.int64(11)

In [83]:
df['Cohort']=df['Cohort'].fillna(mean2)

In [84]:
df['Cohort'].isnull().sum()

np.int64(0)

In [85]:
df['Cohort'].unique()

array([1.        , 2.        , 3.        , 5.        , 4.        ,
       9.        , 7.        , 6.        , 2.90032026, 8.        ])

In [86]:
df['Cohort']=df['Cohort'].astype(float)

In [87]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    2509 non-null   int64  
 5   Cohort                          2509 non-null   float64
 6   ER status measured by IHC       2426 non-null   object 
 7   ER Status                       2469 non-null   object 
 8   Neoplasm Histologic Grade       2388 non-null   float64
 9   HER2 status measured by SNP6    1980 non-null   object 
 10  HER2 Status                     1980 non-null   object 
 11  Tumor Other Histologic Subtype  2374 non-null   object 
 12  Hormone Therapy                 19

In [88]:
df['ER status measured by IHC'].unique()

array(['Positve', 'Negative', nan], dtype=object)

In [89]:
df['ER status measured by IHC'].mode()

0    Positve
Name: ER status measured by IHC, dtype: object

In [90]:
df['ER status measured by IHC'].isnull().sum()

np.int64(83)

In [91]:
df['ER status measured by IHC'].value_counts()

ER status measured by IHC
Positve     1817
Negative     609
Name: count, dtype: int64

In [92]:
df['ER status measured by IHC']=df['ER status measured by IHC'].map({'Positve':1, 'Negative':0, np.nan:1})

In [93]:
df['ER status measured by IHC'].value_counts()

ER status measured by IHC
1    1900
0     609
Name: count, dtype: int64

In [94]:
df['ER status measured by IHC'].isnull().sum()

np.int64(0)

In [95]:
df['ER status measured by IHC']=df['ER status measured by IHC'].astype(int)

In [96]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    2509 non-null   int64  
 5   Cohort                          2509 non-null   float64
 6   ER status measured by IHC       2509 non-null   int64  
 7   ER Status                       2469 non-null   object 
 8   Neoplasm Histologic Grade       2388 non-null   float64
 9   HER2 status measured by SNP6    1980 non-null   object 
 10  HER2 Status                     1980 non-null   object 
 11  Tumor Other Histologic Subtype  2374 non-null   object 
 12  Hormone Therapy                 19

In [97]:
df['ER Status'].unique()

array(['Positive', 'Negative', nan], dtype=object)

In [98]:
df['ER Status'].value_counts()

ER Status
Positive    1825
Negative     644
Name: count, dtype: int64

In [99]:
df['ER Status']=df['ER Status'].map({'Positive':1, 'Negative':0, np.nan:1})

In [100]:
df['ER Status'].value_counts()

ER Status
1    1865
0     644
Name: count, dtype: int64

In [101]:
df['ER Status']=df['ER Status'].astype(int)

In [102]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    2509 non-null   int64  
 5   Cohort                          2509 non-null   float64
 6   ER status measured by IHC       2509 non-null   int64  
 7   ER Status                       2509 non-null   int64  
 8   Neoplasm Histologic Grade       2388 non-null   float64
 9   HER2 status measured by SNP6    1980 non-null   object 
 10  HER2 Status                     1980 non-null   object 
 11  Tumor Other Histologic Subtype  2374 non-null   object 
 12  Hormone Therapy                 19

In [103]:
df['Neoplasm Histologic Grade'].unique()

array([ 3.,  2.,  1., nan])

In [104]:
mean3=df['Neoplasm Histologic Grade'].mean()

In [105]:
mean3

np.float64(2.4120603015075375)

In [106]:
df['Neoplasm Histologic Grade']=df['Neoplasm Histologic Grade'].fillna(mean2)

In [107]:
df['Neoplasm Histologic Grade'].unique()

array([3.        , 2.        , 1.        , 2.90032026])

In [108]:
df['Neoplasm Histologic Grade'].dtype

dtype('float64')

In [109]:
df['HER2 status measured by SNP6'].unique()

array(['Neutral', 'Loss', nan, 'Gain', 'Undef'], dtype=object)

In [110]:
df['HER2 status measured by SNP6'].value_counts()

HER2 status measured by SNP6
Neutral    1436
Gain        438
Loss        101
Undef         5
Name: count, dtype: int64

In [111]:
df['HER2 status measured by SNP6']=df['HER2 status measured by SNP6'].map({'Neutral':1, 'Loss':2, 'Gain':0, 'Undef':3, np.nan:1})

In [112]:
df['HER2 status measured by SNP6'].unique()

array([1, 2, 0, 3])

In [113]:
df['HER2 status measured by SNP6'].isnull().sum()

np.int64(0)

In [114]:
df['HER2 status measured by SNP6']=df['HER2 status measured by SNP6'].astype(int)

In [115]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    2509 non-null   int64  
 5   Cohort                          2509 non-null   float64
 6   ER status measured by IHC       2509 non-null   int64  
 7   ER Status                       2509 non-null   int64  
 8   Neoplasm Histologic Grade       2509 non-null   float64
 9   HER2 status measured by SNP6    2509 non-null   int64  
 10  HER2 Status                     1980 non-null   object 
 11  Tumor Other Histologic Subtype  2374 non-null   object 
 12  Hormone Therapy                 19

In [116]:
df['HER2 Status'].unique()

array(['Negative', nan, 'Positive'], dtype=object)

In [117]:
df['HER2 Status'].isnull().sum()

np.int64(529)

In [118]:
df['HER2 Status'].value_counts()

HER2 Status
Negative    1733
Positive     247
Name: count, dtype: int64

In [119]:
df['HER2 Status']=df['HER2 Status'].map({'Negative':1, 'Positive':0, np.nan:1})

In [120]:
df['HER2 Status'].unique()

array([1, 0])

In [121]:
df['HER2 Status']=df['HER2 Status'].astype(int)

In [122]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    2509 non-null   int64  
 5   Cohort                          2509 non-null   float64
 6   ER status measured by IHC       2509 non-null   int64  
 7   ER Status                       2509 non-null   int64  
 8   Neoplasm Histologic Grade       2509 non-null   float64
 9   HER2 status measured by SNP6    2509 non-null   int64  
 10  HER2 Status                     2509 non-null   int64  
 11  Tumor Other Histologic Subtype  2374 non-null   object 
 12  Hormone Therapy                 19

In [123]:
df['Tumor Other Histologic Subtype'].unique()

array(['Ductal/NST', 'Mixed', 'Lobular', 'Tubular/ cribriform', nan,
       'Mucinous', 'Medullary', 'Other', 'Metaplastic'], dtype=object)

In [124]:
encoded3=df.groupby('Tumor Other Histologic Subtype')['Overall Survival Status'].mean()

In [125]:
df['Tumor_Other_Histologic_Subtype']=df['Tumor Other Histologic Subtype'].map(encoded3)

In [126]:
df['Tumor_Other_Histologic_Subtype'].unique()

array([0.65690608, 0.7063197 , 0.6875    , 0.34782609,        nan,
       0.48      , 0.65625   , 0.42857143, 1.        ])

In [127]:
mean5=df['Tumor_Other_Histologic_Subtype'].mean()

In [128]:
mean5

np.float64(0.6583824768323505)

In [129]:
df['Tumor_Other_Histologic_Subtype']=df['Tumor_Other_Histologic_Subtype'].fillna(mean5)

In [130]:
df['Tumor_Other_Histologic_Subtype'].unique()

array([0.65690608, 0.7063197 , 0.6875    , 0.34782609, 0.65838248,
       0.48      , 0.65625   , 0.42857143, 1.        ])

In [131]:
df['Tumor_Other_Histologic_Subtype'].dtype

dtype('float64')

In [132]:
df.drop('Tumor Other Histologic Subtype', axis=1, inplace=True)

In [133]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    2509 non-null   int64  
 5   Cohort                          2509 non-null   float64
 6   ER status measured by IHC       2509 non-null   int64  
 7   ER Status                       2509 non-null   int64  
 8   Neoplasm Histologic Grade       2509 non-null   float64
 9   HER2 status measured by SNP6    2509 non-null   int64  
 10  HER2 Status                     2509 non-null   int64  
 11  Hormone Therapy                 1980 non-null   object 
 12  Inferred Menopausal State       19

In [134]:
df['Hormone Therapy'].unique()

array(['Yes', 'No', nan], dtype=object)

In [135]:
df['Hormone Therapy'].value_counts()

Hormone Therapy
Yes    1216
No      764
Name: count, dtype: int64

In [136]:
df['Hormone Therapy'].isnull().sum()

np.int64(529)

In [137]:
df['Hormone Therapy']=df['Hormone Therapy'].map({'Yes':1, 'No':0, np.nan:1})

In [138]:
df['Hormone Therapy'].unique()

array([1, 0])

In [139]:
df['Hormone Therapy'].dtype

dtype('int64')

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2509 entries, 0 to 2508
Data columns (total 33 columns):
 #   Column                          Non-Null Count  Dtype  
---  ------                          --------------  -----  
 0   Age at Diagnosis                2509 non-null   float64
 1   Type of Breast Surgery          2509 non-null   int64  
 2   Cancer Type                     2509 non-null   int64  
 3   Cellularity                     2509 non-null   int64  
 4   Chemotherapy                    2509 non-null   int64  
 5   Cohort                          2509 non-null   float64
 6   ER status measured by IHC       2509 non-null   int64  
 7   ER Status                       2509 non-null   int64  
 8   Neoplasm Histologic Grade       2509 non-null   float64
 9   HER2 status measured by SNP6    2509 non-null   int64  
 10  HER2 Status                     2509 non-null   int64  
 11  Hormone Therapy                 2509 non-null   int64  
 12  Inferred Menopausal State       19

In [141]:
df['Inferred Menopausal State'].unique()

array(['Post', 'Pre', nan], dtype=object)

In [142]:
df['Inferred Menopausal State'].value_counts()

Inferred Menopausal State
Post    1556
Pre      424
Name: count, dtype: int64

In [146]:
df['Inferred Menopausal State']=df['Inferred Menopausal State'].map({'Post':1, 'Pre':0, np.nan:1})

In [147]:
df['Inferred Menopausal State'].unique()

array([1, 0])

In [148]:
df['Inferred Menopausal State'].dtype

dtype('int64')

In [149]:
df.to_csv('Breast Cancer METABRIC_half.csv',index=False)